### ISSUE TITLE
Crash when using with AE2

### ISSUE THREAD

**Issue by Sakreton** [Shadows-of-Fire/Toast-Control#31]
Got Told this is probably on your end.
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6750

AE2 generates a toast(?) when a crafting job finishes. More information below.

Describe the bug
My game crashed 3 times and this perfectly synchronises with the completion of a crafting job, i cant see the pop up and had no terminal open at the time. Cant confirm ae2 is the cause though, cant reproduce.

Cant reproduce relibably, afaik it happend only when i had the terminal open and when crafting items from mekanism, take the last one with a grain of salt.

Additional details
Playing on a server, Server stays up.
appliedenergistics2-forge-12.8.3
Toast Control 7.0.0

Which minecraft version are you using?
1.19

On which mod loaders does it happen?
Forge

Crash log
https://gist.github.com/Sakreton/cc78000f72d8f69fc4ae3a74bde0cfd8

**Comment by Shadows-of-Fire** [comment]
This is potentially on my end but it appears there is another factor at play - Advancement Plaques is screwing with TC internals https://github.com/AHilyard/AdvancementPlaques/blob/1.19/src/main/java/com/anthonyhilyard/advancementplaques/AdvancementPlaquesToastGui.java

I can implement something that may prevent this particular crash but I have no idea what other issues may arise from this.

Advancement Plaques should really be using their own GUI Component and utilizing the ToastAddEvent to capture advancement toasts instead of hijacking the toast component.

**Comment by Sakreton** [comment]
Can't really add to that, i could also report it to advancement plaques and see what they know.

**Comment by AndreiTS** [comment]
I'm having the same crash when joining my server. I don't have advancement plaques installed.
[crash-2022-12-22_23.29.09-client.txt](https://github.com/Shadows-of-Fire/Toast-Control/files/10291634/crash-2022-12-22_23.29.09-client.txt)

**Comment by Peca21** [comment]
Also crashing
https://mcpaste.io/bfa9682e5227604a

**Comment by Shadows-of-Fire** [comment]
Closing as I don't think this is resolvable by me.
